import type { Carrier } from "@/entities/carrier/model/types";
import type { Order } from "@/entities/order/model/types";

export const carriers: Carrier[] = [
  { id: "carrier-1", name: "Northline Freight", mcNumber: "MC-918244", rating: 4.8 },
  { id: "carrier-2", name: "Blue Ridge Logistics", mcNumber: "MC-104882", rating: 4.6 },
  { id: "carrier-3", name: "Summit Express", mcNumber: "MC-552019", rating: 4.9 },
  { id: "carrier-4", name: "Metro Haul", mcNumber: "MC-771230", rating: 4.4 },
];

export let orders: Order[] = [
  {
    id: "ord-1",
    referenceNumber: "REF-4511829208",
    status: "pending",
    clientName: "Acme Foods",
    carrierId: "carrier-1",
    carrierName: "Northline Freight",
    equipmentType: "Dry Van",
    loadType: "FTL",
    rate: 950,
    weight: 1360,
    notes: "Call before pickup.",
    createdAt: "2026-04-22T09:00:00.000Z",
    updatedAt: "2026-04-22T09:00:00.000Z",
    stops: [
      {
        id: "stop-1",
        kind: "pickup",
        city: "Chicago",
        state: "IL",
        zip: "60601",
        locationName: "Acme Warehouse",
        appointmentType: "fixed",
        appointmentDate: "2026-05-06",
        appointmentTime: "09:00",
        notes: "",
      },
      {
        id: "stop-2",
        kind: "dropoff",
        city: "Dallas",
        state: "TX",
        zip: "75201",
        locationName: "Dallas DC",
        appointmentType: "window",
        appointmentDate: "2026-05-08",
        appointmentTime: "13:00",
        notes: "Receiving gate 4.",
      },
    ],
  },
  {
    id: "ord-2",
    referenceNumber: "REF-4451182817",
    status: "in_transit",
    clientName: "Fresh Valley",
    carrierId: "carrier-2",
    carrierName: "Blue Ridge Logistics",
    equipmentType: "Reefer",
    loadType: "FTL",
    rate: 1150,
    weight: 285,
    notes: "Keep temperature at 34F.",
    createdAt: "2026-04-20T09:00:00.000Z",
    updatedAt: "2026-04-23T09:00:00.000Z",
    stops: [
      {
        id: "stop-3",
        kind: "pickup",
        city: "Denver",
        state: "CO",
        zip: "80202",
        locationName: "Cold Storage West",
        appointmentType: "fcfs",
        appointmentDate: "2026-05-04",
        appointmentTime: "08:00",
        notes: "",
      },
      {
        id: "stop-4",
        kind: "stop",
        city: "Oklahoma City",
        state: "OK",
        zip: "73102",
        locationName: "Crossdock OKC",
        appointmentType: "fixed",
        appointmentDate: "2026-05-05",
        appointmentTime: "16:00",
        notes: "",
      },
      {
        id: "stop-5",
        kind: "dropoff",
        city: "Atlanta",
        state: "GA",
        zip: "30303",
        locationName: "Atlanta Market",
        appointmentType: "fixed",
        appointmentDate: "2026-05-07",
        appointmentTime: "10:30",
        notes: "",
      },
    ],
  },
  {
    id: "ord-3",
    referenceNumber: "REF-4511826012",
    status: "delivered",
    clientName: "BuildRight",
    carrierId: "carrier-3",
    carrierName: "Summit Express",
    equipmentType: "Flatbed",
    loadType: "Partial",
    rate: 1855,
    weight: 24600,
    notes: "",
    createdAt: "2026-04-15T09:00:00.000Z",
    updatedAt: "2026-04-21T09:00:00.000Z",
    stops: [
      {
        id: "stop-6",
        kind: "pickup",
        city: "Phoenix",
        state: "AZ",
        zip: "85004",
        locationName: "BuildRight Yard",
        appointmentType: "fixed",
        appointmentDate: "2026-04-28",
        appointmentTime: "11:00",
        notes: "",
      },
      {
        id: "stop-7",
        kind: "dropoff",
        city: "Las Vegas",
        state: "NV",
        zip: "89101",
        locationName: "North Site",
        appointmentType: "fcfs",
        appointmentDate: "2026-04-29",
        appointmentTime: "14:00",
        notes: "",
      },
    ],
  },
];

export function setOrders(nextOrders: Order[]) {
  orders = nextOrders;
}
